spring.application.name=TaskManagement
server.port=8081

# Database — env variable hoặc default local
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT — env variable
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Mail
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dyrksdywm}
cloudinary.api-key=${CLOUDINARY_API_KEY:947124991745588}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# CORS
cors.allowed-origins=${CORS_ORIGINS:*}

# Task reminder
task.reminder.cron=0 0 8 * * *
task.reminder.hours-before-deadline=24
verification.code.expiration-minutes=10

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.try-it-out-enabled=true

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB